Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-10:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM4': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-11:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM4': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM1': WindowsError(2, '\xc1\xf6\xc1\xa4\xb5\xc8 \xc6\xc4\xc0\xcf\xc0\xbb \xc3\xa3\xc0\xbb \xbc\xf6 \xbe\xf8\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM1': WindowsError(2, '\xc1\xf6\xc1\xa4\xb5\xc8 \xc6\xc4\xc0\xcf\xc0\xbb \xc3\xa3\xc0\xbb \xbc\xf6 \xbe\xf8\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-3:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-6:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-8:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-11:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-13:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-15:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

Exception in thread Thread-16:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "esp8266_flasher.py", line 19, in run
  File "downloader.pyo", line 54, in __init__
  File "serial\serialwin32.pyo", line 38, in __init__
  File "serial\serialutil.pyo", line 282, in __init__
  File "serial\serialwin32.pyo", line 66, in open
SerialException: could not open port 'COM3': WindowsError(5, '\xbe\xd7\xbc\xbc\xbd\xba\xb0\xa1 \xb0\xc5\xba\xce\xb5\xc7\xbe\xfa\xbd\xc0\xb4\xcf\xb4\xd9.')

